config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :recipes, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if params[:search]
      @recipes = Recipe.search(params[:search]).order("created_at DESC")
    else
      @recipes = Recipe.all.order("created_at DESC")
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    if params[:search]
      @recipes = Recipe.search(params[:search]).order("created_at DESC")
    elsif params[:category]
      @recipes = Recipe.all
    elsif params[:subcategory].present?
      @recipes = Recipe.search(params[:subcategory]).order("created_at DESC")
    else
      @recipes = Recipe.all.order("created_at DESC")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<body>
  <div class="headers-box text-left">
    <h3 class="sub-heading">FAST & EASY LOW CARB RECIPE IDEAS</h3>
    <h1 class="heading text-blue">Recipes</h1>
  </div>
  <div class="search">
    <%= form_tag(recipes_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Recipes..", class: "search-input" %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
          <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>
  <div class="card-category color-yellow d-flex flex-column">
    <%= link_to recipes_path do %>
      <h3>Breakfast</h3>
      <p class="sub-heading-white">FAST & EASY BREAKFAST IDEAS UNDER 10G NET CARBS</p>
    <% end %>
  </div>

  <div class="card-category color-pink d-flex flex-column">
    <%= link_to recipes_path do %>
      <h3>Lunch & Dinner</h3>
      <p class="sub-heading-white">DELICIOUS LOW CARB MEALS FOR ANY TIME</p>
    <% end %>
  </div>

  <div class="card-category color-light-blue d-flex flex-column">
    <%= link_to recipes_path do %>
      <h3>Soups & Salads</h3>
      <p class="sub-heading-white">LIGHT SOUPS & TO ENJOY ANY TIME</p>
    <% end %>
  </div>

  <div class="card-category color-green d-flex flex-column">
    <%= link_to recipes_path do %>
      <h3>Snacks & Sides</h3>
      <p class="sub-heading-white">SOMETHING FOR INBETWEEN & ON THE SIDE</p>
      <% end %>
  </div>

  <div class="card-category color-red d-flex flex-column">
    <%= link_to recipes_path do %>
      <h3>Condiments</h3>
      <p class="sub-heading-white">HEALTHY CONDIMENT RECIPES FOR MORE FLAVOUR</p>
    <% end %>
  </div>

</body>

app/views/recipes/index.html.erb
 <body>
  <div class="headers-box text-left">
    <h3 class="sub-heading"><%= @recipes.count %>+ DELICIOUS BREAKFAST IDEAS</h3>
    <h1 class="heading text-blue">Breakfast</h1>
  </div>

  <div class="search">
    <%= form_tag(recipes_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Recipes..", class: "search-input" %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
          <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>



  <div class="tabs d-flex flex-row justify-content-around">

    <%= form_tag(recipes_path, :method => "get") do %>
      <%= text_field_tag :category, params[:category], value:"breakfast", hidden: true %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
        <div class="pink-box">all</div>
      <% end %>
    <% end %>

    <%= form_tag(recipes_path, :method => "get") do %>
      <%= text_field_tag :subcategory, params[:subcategory], value: "egg", hidden: true %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
         <div class="pink-box">egg</div>
      <% end %>
    <% end %>

    <%= form_tag(recipes_path, :method => "get") do %>
      <%= text_field_tag :subcategory, params[:subcategory], value: "smoothie", hidden: true %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
        <div class="pink-box">smoothie</div>
      <% end %>
    <% end %>

    <%= form_tag(recipes_path, :method => "get") do %>
      <%= text_field_tag :subcategory, params[:subcategory], value: "toast", hidden: true %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
        <div class="pink-box">bread</div>
      <% end %>
    <% end %>

  </div>

  <% @recipes.each do |recipe| %>
    <div class="card-product">
      <%= image_tag recipe.picture %>


      <div class="card-product-infos">
        <span class="prep"><i class="far fa-clock"></i> <%= recipe.preptime %></span>
        <h2><%= recipe.name %></h2>
        <p><%= recipe.description %></p>
      </div>
    </div>
  <% end %>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>